### ISSUE TITLE
raml-cop stoped working after 1.1.25 version of raml-1-parser released

### ISSUE THREAD

**Issue by t1maccapp** [thebinarypenguin/raml-cop#14]
Hi, I use raml-cop in my CI jobs. After new release (1.1.25) of raml-1-parser raml-cop throws an error

```
Error: Cannot find module 'raml-1-parser'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/???/raml-cop/src/raml-cop.js:9:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

Steps to reproduce:
```
1. npm install raml-cop --silent
2. node_modules/raml-cop/src/raml-cop.js .raml/api.raml
```

**Comment by t1maccapp** [comment]
Found issue in raml-1-parser repository: https://github.com/raml-org/raml-js-parser-2/issues/755
